services:
  mysql:
    image: mysql:8
    container_name: mysql-url-shortener
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortener_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  tomcat:
    image: tomcat:10.1-jdk17
    container_name: tomcat-url-shortener
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
    volumes:
      - ./target/bm470.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - mysql

volumes:
  mysql_data:
